site_name: REMnux Docs
site_url: http://remnux.org/docs
site_description: Documentation for REMnux, a free toolkit for assisting malware analysts with reverse-engineering malicious software.
site_favicon: favicon.ico
theme: readthedocs

pages:
- ['index.md', 'Home']
- ['distro/get.md', 'REMnux Distro', 'Get the REMnux Distro']
- ['distro/tools.md', 'REMnux Distro', 'Tools Installed on REMnux']
- ['distro/use.md', 'REMnux Distro', 'Using REMnux and Its Tools']
- ['containers/about.md', 'Application Containers', 'Docker Images for Malware Analysis']
- ['expand/contribute.md', 'Expand REMnux', 'Contribute Your Expertise']
